apiVersion: v1
kind: Pod
metadata:
  name: supbox
spec:
  containers:
  - name: supbox
    image: ghcr.io/guctum/busybox-curl:amd64
    imagePullPolicy: Always
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    resources:
      limits:
        memory: "50Mi"
        cpu: "50m"